**Array** Examples (py3)

In [43]:
two_dimension_array_wrong = [[0]*3] * 4
two_dimension_array_wrong
#each row is a reference to a list
print("two_dimension_array_wrong row data type is:{}".format(type(two_dimension_array_wrong[1]))) 
# set value
two_dimension_array_wrong[0][1] = 2
# all column changed
print(two_dimension_array_wrong)

# Create by [[0] * cols for i in range(rows)]
two_dimension_array = [[0] * 3 for i in range(4)]
two_dimension_array[0][1] = 2
print(two_dimension_array)

outlier_indexs = [[] for i in range(6)]
outlier_indexs[0].append(1)
# list extend multi elements
outlier_indexs[3].extend([5,6,7,8,9])
print(outlier_indexs)
# list iterate by enumerate
for i, value in enumerate(outlier_indexs[3]):
    print("The {}th value is:{}".format(i,value))

two_dimension_array_wrong row data type is:<class 'list'>
[[0, 2, 0], [0, 2, 0], [0, 2, 0], [0, 2, 0]]
[[0, 2, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]]
[[1], [], [], [5, 6, 7, 8, 9], [], []]
The 0th value is:5
The 1th value is:6
The 2th value is:7
The 3th value is:8
The 4th value is:9


**DataFrame** Examples

In [14]:
# create DataFrames
# 1, create from dictionary
import pandas as pd
import numpy as np
data = {'col_1':[1,2,3],'col_2':[2,3,4],'col_3':[3,4,5]}
frame = pd.DataFrame(data)
print(frame)

   col_1  col_2  col_3
0      1      2      3
1      2      3      4
2      3      4      5


In [20]:
# 2, create from array
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)
frame_array = pd.DataFrame(array,columns=['A','B','C'])
print(frame_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9
