 # 如下示例程序：
 * 数组(Array)及多维数组
 * DataFrame及其应用
 * Dictionary及其应用
 * Math Operations

## Array Examples (py3)

In [44]:
two_dimension_array_wrong = [[0]*3] * 4
two_dimension_array_wrong
#each row is a reference to a list
print("two_dimension_array_wrong row data type is:{}".format(type(two_dimension_array_wrong[1]))) 
# set value
two_dimension_array_wrong[0][1] = 2
# all column changed
print(two_dimension_array_wrong)

# Create by [[0] * cols for i in range(rows)]
two_dimension_array = [[0] * 3 for i in range(4)]
two_dimension_array[0][1] = 2
print(two_dimension_array)

outlier_indexs = [[] for i in range(6)]
outlier_indexs[0].append(1)
# list extend multi elements
outlier_indexs[3].extend([5,6,7,8,9])
print(outlier_indexs)
# list iterate by enumerate
for i, value in enumerate(outlier_indexs[3]):
    print("The {}th value is:{}".format(i,value))

two_dimension_array_wrong row data type is:<class 'list'>
[[0, 2, 0], [0, 2, 0], [0, 2, 0], [0, 2, 0]]
[[0, 2, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]]
[[1], [], [], [5, 6, 7, 8, 9], [], []]
The 0th value is:5
The 1th value is:6
The 2th value is:7
The 3th value is:8
The 4th value is:9


In [91]:
# 2 dimention array
import numpy as np
from sklearn import preprocessing

array = []
a1 = ['a','b','c']
b1 = ['d','e','f']
array.append(a1)
array.append(b1)
print("The array:")
print(array)

full_x = array
full_x = np.array(array)
print(full_x)
array = np.array(array)
print(array.shape[1])
print(type(array))

les = []
for i in range(array.shape[1]):
    le = preprocessing.LabelEncoder()
    le.fit(full_x[:,i])
    les.append(le)
    array[:,i] =le.transform(array[:,i])
print(les)
print(array)
print(full_x)
array = array.astype(int)
print(array)

print(full_x[..., [1]])

The array:
[['a', 'b', 'c'], ['d', 'e', 'f']]
[['a' 'b' 'c']
 ['d' 'e' 'f']]
3
<class 'numpy.ndarray'>
[LabelEncoder(), LabelEncoder(), LabelEncoder()]
[['0' '0' '0']
 ['1' '1' '1']]
[['a' 'b' 'c']
 ['d' 'e' 'f']]
[[0 0 0]
 [1 1 1]]
[['b']
 ['e']]


## DataFrame Examples

In [63]:
# create DataFrames
# 1, create from dictionary
import pandas as pd
import numpy as np
data = {'col_1':[1,2,3],'col_2':[2,3,4],'col_3':[3,4,5]}
frame = pd.DataFrame(data)
print("Init frame:")
print(frame)

len(frame['col_1'].unique())

new_frame = frame.drop(['col_2'], axis =1)
print("The df droped from initial df:")
print(new_frame)
print("The df stay unchanged:")
print(frame)

print("select row")
print(frame.iloc[1].values.tolist())

Init frame:
   col_1  col_2  col_3
0      1      2      3
1      2      3      4
2      3      4      5
The df droped from initial df:
   col_1  col_3
0      1      3
1      2      4
2      3      5
The df stay unchanged:
   col_1  col_2  col_3
0      1      2      3
1      2      3      4
2      3      4      5
select row
[2, 3, 4]


In [62]:
# Append to dataframe
data_append = {'col_1':[4,5],'col_2':[5,6],'col_3':[6,7]}
frame_append = pd.DataFrame(data_append)
print("df after append new row:")
frame.append(frame_append,ignore_index=True)

print(frame)

df after append new row:
   col_1  col_2  col_3
0      1      2      3
1      2      3      4
2      3      4      5
3      4      5      6
4      5      6      7


In [4]:
# 2, create from array
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)
frame_array = pd.DataFrame(array,columns=['A','B','C'])
print(frame_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


In [5]:
# 3，Iterate dataframe
for index, row in frame_array.iterrows():
    print("Sum of current row {} is {}".format(index, row.sum()))

Sum of current row 0 is 6
Sum of current row 1 is 15
Sum of current row 2 is 24


In [72]:
# Date Time
date = pd.date_range('1/1/2014', periods=100)
data = np.random.normal(0.5,2,100)
df = pd.DataFrame({'date':date, 'data':data})
#df = df.set_index('date')
df.groupby(df['date'].apply(lambda x:x.month)).first()

#len(df['data'].unique())

data       date
date                     
1     2.065044 2014-01-01
2     4.527587 2014-02-01
3     1.162860 2014-03-01
4     0.966050 2014-04-01

In [64]:
# Aggregate
colors = ['red','green','red','red','green']
#colors = ['2014-05-01','2014-08-07','2014-05-12','2014-08-14','2017-02-13']
foods = ['eggs','ham','eggs','eggs','ham']

index = pd.MultiIndex.from_arrays([colors,foods],names=['color','food'])
df = pd.DataFrame(np.random.randn(5,2),index=index)
df.columns = ['a','b']
#df['date']=colors

#df['date']=pd.to_datetime(df['date'],format='%Y-%m-%d')

print(df)

grouped = df.groupby(level=['color','food'])
#grouped = df.groupby(df['date'].apply(lambda x:x.month))

aggregated = grouped.aggregate(np.sum)
print(aggregated)
#print(aggregated.reset_index())
#print(aggregated.describe())

#df[:,['color']]

                   a         b
color food                    
red   eggs  0.809832  0.332811
green ham   0.555660  0.571370
red   eggs  0.042514  0.799528
      eggs -0.370897 -0.195957
green ham  -0.917384  1.034452
                   a         b
color food                    
green ham  -0.361724  1.605822
red   eggs  0.481449  0.936383


In [47]:
# Example:
import pandas as pd
import datetime
import numpy as np

# Create a datetime variable for today
base = datetime.datetime.today()
# Create a list variable that creates 365 days of rows of datetime values
date_list = [base - datetime.timedelta(days=x) for x in range(0, 365)]

# Create a list variable of 365 numeric values
score_list = list(np.random.randint(low=1, high=1000, size=365))

# Create an empty dataframe
df = pd.DataFrame()

# Create a column from the datetime variable
df['datetime'] = date_list
# Convert that column into a datetime datatype
df['datetime'] = pd.to_datetime(df['datetime'])
# Set the datetime column as the index
df.index = df['datetime']
# Create a column from the numeric score variable
df['score'] = score_list

df.head()

# Group the data by month, and take the sum for each group (i.e. each month)
print(df.resample('M').sum())

            score
datetime         
2016-08-31   7901
2016-09-30  15020
2016-10-31  16890
2016-11-30  17011
2016-12-31  17579
2017-01-31  14793
2017-02-28  11853
2017-03-31  15256
2017-04-30  16389
2017-05-31  14822
2017-06-30  11569
2017-07-31  16880
2017-08-31   8333


 ## **Dictionary**的使用

In [1]:
# key in dictionary must be not mutable
dict1 = {1:"apple",2:"orange",3: "peach"}
for key, value in dict1.items():
    print("key of {} have the value as {}".format(key, value))

# update a dictionary by another dictionary
dict2 = {1:"cat"}
dict1.update(dict2)
print(dict1)

# get from dictionary
item1 = dict1.get(4,100) + 1
print("Get with default value result: {}".format(item1))

key of 1 have the value as apple
key of 2 have the value as orange
key of 3 have the value as peach
{1: 'cat', 2: 'orange', 3: 'peach'}
Get with default value result: 101


In [6]:
inner_dict = {"1_1":"inner_1.1","1_2":"inner_1.2"}
dict1[2] = inner_dict
print(dict1.get(5,None))

None


In [13]:
count = { 'a': 120, 'b': 120, 'c': 100 }
highest = max(count.values())
print highest
maxs =[k for k,v in count.items() if v == highest]
print len(maxs)
print maxs[0]
print tuple(sorted(count.items()))

120
2
a
(('a', 120), ('b', 120), ('c', 100))


## Math Operations

In [45]:
import math
#　ｍｏｄ　ｉｓ　％
count = 5 
cols = 5

plot_row_index = math.ceil(count / cols) - 1
plot_col_index = count - plot_row_index * cols -1    

print(type(plot_row_index))

print("Row index is: {0}".format(plot_row_index))

print("Col index is: {0}".format(plot_col_index))

<class 'int'>
Row index is: 0
Col index is: 4
